# Generated by Django 4.2.28 on 2026-02-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enrollment_open', models.BooleanField(default=False)),
                ('enrollment_start_date', models.DateTimeField(blank=True, null=True)),
                ('enrollment_end_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
