# Generated by Django 4.2.28 on 2026-02-12 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_alter_instructor_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=120, unique=True, verbose_name='Ders Kodu')),
                ('course_name', models.CharField(max_length=100, verbose_name='Ders Kodu')),
                ('course_detail', models.TextField(blank=True, null=True, verbose_name='Ders Kodu')),
                ('credit', models.IntegerField(default=3, verbose_name='Ders Kredisi')),
                ('akts', models.IntegerField(default=5, verbose_name="Dersin Akts'si")),
                ('capacity', models.IntegerField(default=50, verbose_name='Dersin Kontenjanı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.instructor', verbose_name='Instructor')),
            ],
        ),
    ]
