# Generated by Django 4.2.28 on 2026-02-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='bolum',
            field=models.CharField(choices=[('CENG', 'Ceng'), ('MATH', 'Math'), ('BIL', 'Bil')], default='MATH', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_detail',
            field=models.TextField(blank=True, null=True, verbose_name='Dersin İçeriği'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=100, verbose_name='Ders İsmi'),
        ),
    ]
