# Generated by Django 4.2.28 on 2026-02-17 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_instructor_title'),
        ('courses', '0002_course_bolum_alter_course_course_detail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='bolum',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='akts',
            new_name='ects',
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.instructor', verbose_name='Dersin Hocası'),
        ),
    ]
