# Generated by Django 4.2.28 on 2026-02-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_bolum_course_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Department',
            new_name='department',
        ),
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.IntegerField(choices=[(1, '1.SINIF'), (2, '2.SINIF'), (3, '3.SINIF'), (4, '4.SINIF')], default=1, max_length=10),
        ),
    ]
