# Generated by Django 4.2.28 on 2026-02-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_department_course_department_course_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.IntegerField(choices=[(1, '1.SINIF'), (2, '2.SINIF'), (3, '3.SINIF'), (4, '4.SINIF')], default=1),
        ),
    ]
