# Generated by Django 4.2.28 on 2026-02-20 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_instructor_alter_grade_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.TextField(choices=[('Spring', 'Spring'), ('Autumn', 'Autumn')])),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.TextField(choices=[('CENG', 'CENG'), ('MATH', 'MATH'), ('SWE', 'SWE')]),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.semester'),
        ),
    ]
