# Generated by Django 4.2.28 on 2026-02-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_semester_alter_department_department_course_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Semester Status'),
        ),
    ]
