# Generated by Django 4.2.28 on 2026-02-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_semester_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='year',
            field=models.IntegerField(default=2026),
        ),
    ]
