# Generated by Django 4.2.29 on 2026-03-05 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_remove_course_capacity_remove_course_classroom_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='section',
            name='section_number',
        ),
    ]
