# Generated by Django 4.2.29 on 2026-03-05 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_remove_course_capacity_section_section_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.RemoveField(
            model_name='course',
            name='grade',
        ),
        migrations.AddField(
            model_name='section',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections_department', to='courses.department'),
        ),
        migrations.AddField(
            model_name='section',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections_grade', to='courses.grade'),
        ),
    ]
