# Generated by Django 4.2.29 on 2026-03-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_remove_course_department_remove_course_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
