# Generated by Django 4.2.29 on 2026-03-06 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_instructor_deleted_at_instructor_is_deleted_and_more'),
        ('courses', '0022_alter_section_section_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='section_id',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.section'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='users.student'),
        ),
        migrations.AlterField(
            model_name='section',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, default=50, null=True),
        ),
    ]
