# Generated by Django 4.2.29 on 2026-03-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_remove_section_section_id_alter_enrollment_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='letter_grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
