# Generated by Django 4.2.29 on 2026-03-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_enrollment_letter_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_active_makeup_grade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='makeup_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
