# Generated by Django 4.2.29 on 2026-03-09 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_enrollment_is_active_makeup_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('total_ecs_requrired', models.IntegerField(default=240)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.department')),
            ],
            options={
                'unique_together': {('department', 'year')},
            },
        ),
        migrations.CreateModel(
            name='CurriculumDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('course_type', models.CharField(choices=[('Z', 'Zorunlu'), ('S', 'Seçmeli')], default='Z', max_length=1)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
                ('curriculum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail', to='courses.curriculum')),
            ],
            options={
                'unique_together': {('curriculum', 'course')},
            },
        ),
    ]
