# Generated by Django 4.2.29 on 2026-03-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_curriculum_curriculumdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='is_prerequisites', to='courses.course'),
        ),
    ]
