# Generated by Django 4.2.29 on 2026-03-11 12:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0027_course_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
