# Generated by Django 4.2.29 on 2026-03-12 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_answer_liked_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-is_accepted', '-upvotes']},
        ),
    ]
