# Generated by Django 4.2.28 on 2026-02-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student_enrollment_date_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'ADMIN'), ('Instructor', 'INSTRUCTOR'), ('Student', 'STUDENT')], default='ADMIN', max_length=20),
            preserve_default=False,
        ),
    ]
