# Generated by Django 4.2.28 on 2026-02-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='title',
            field=models.CharField(choices=[('PROF', 'Profesör'), ('ASSOC_PROF', 'Doçent'), ('ASST_PROF', 'Dr. Öğr. Üyesi'), ('LECT', 'Öğretim Görevlisi'), ('RA', 'Araştırma Görevlisi')], default='LECT', max_length=10, verbose_name='Ünvan'),
        ),
    ]
