# Generated by Django 4.2.28 on 2026-02-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_bolum_course_department_and_more'),
        ('users', '0005_alter_instructor_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='courses.course', verbose_name='Kayıtlı Dersler'),
        ),
    ]
