# Generated by Django 4.2.28 on 2026-02-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, choices=[('CENG', 'Ceng'), ('MATH', 'Math'), ('BIL', 'Bil')], max_length=120),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.IntegerField(choices=[(1, '1.SINIF'), (2, '2.SINIF'), (3, '3.SINIF'), (4, '4.SINIF')], default=1, max_length=10),
        ),
    ]
