# Generated by Django 4.2.28 on 2026-02-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_student_department_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(choices=[(1, '1.SINIF'), (2, '2.SINIF'), (3, '3.SINIF'), (4, '4.SINIF')], default=1),
        ),
    ]
