# Generated by Django 4.2.28 on 2026-02-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_student_department_alter_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='department',
            field=models.CharField(blank=True, choices=[('CENG', 'CENG'), ('MATH', 'MATH')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(choices=[(1, 'Freshman'), (2, 'Sophomore'), (3, 'Junior'), (4, 'Senior')], default=1),
        ),
    ]
