# Generated by Django 4.2.28 on 2026-02-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_instructor_department_alter_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='department',
            field=models.CharField(blank=True, choices=[('CENG', 'CENG'), ('MATH', 'MATH'), ('SWE', 'SWE')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CENG', 'CENG'), ('MATH', 'MATH'), ('SWE', 'SWE')], max_length=120),
        ),
    ]
