# Generated by Django 4.2.28 on 2026-02-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_instructor_department_alter_student_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='title',
            field=models.CharField(choices=[('PROF', 'Professor'), ('ASSOC_PROF', 'Assoc Prof'), ('ASST_PROF', 'Asst Prof'), ('LECT', 'Lecturer'), ('RA', 'Research Asst')], default='LECT', max_length=10, verbose_name='Ünvan'),
        ),
    ]
