# Generated by Django 4.2.29 on 2026-03-06 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_remove_section_section_id_alter_enrollment_section_and_more'),
        ('users', '0013_instructor_deleted_at_instructor_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.section'),
        ),
    ]
